version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Oknoke
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=postgres
      - DB_USER=oknoke
      - DB_PASSWORD=oknoke
      - DB_NAME=oknoke
      - MAILERSEND_API_KEY=${MAILERSEND_API_KEY}
      - EMAIL_TEMPLATE_SIGNUP=${EMAIL_TEMPLATE_SIGNUP}
      - BACKEND_URL=${BACKEND_URL}
      - PRODUCT_URL=${PRODUCT_URL}
      - RECAPTCHA_SITE_KEY=''
      - RECAPTCHA_SECRET_KEY=''
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    entrypoint: ["./run.sh"]

  postgres:  
    image: postgres:13  
    container_name: postgres  
    environment:  
      POSTGRES_DB: oknoke  
      POSTGRES_USER: oknoke  
      POSTGRES_PASSWORD: oknoke  
    ports:  
      - "5432:5432"  # Expose PostgreSQL port  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt/live/gtrag.bot/fullchain.pem:/etc/letsencrypt/live/gtrag.bot/fullchain.pem
      - /etc/letsencrypt/live/gtrag.bot/privkey.pem:/etc/letsencrypt/live/gtrag.bot/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - postgres

volumes:  
  postgres_data: {}  